### ISSUE TITLE
devcontainer.json

### ISSUE THREAD

**Issue by rddaz2013** [scalasm/my-python-kata#71]
the part:
```
  "mounts": [
    // Re-use local Git configuration
    "source=${localEnv:HOME}/.gitconfig,target=/home/vscode/.gitconfig,type=bind,consistency=cached"
  ]
```

**${localEnv:HOME}/** does not work under my WIN11/WSL2 environment ergo the working directory... perhaphs ${localWorkspaceFolder} work better

**Comment by scalasm** [comment]
Interesting ... I am using Windows 10 + WSL2 as my Docker for Desktop backend and it works as expected. 

Are you opening the remote container from a windows folder (e.g., `C:\src\myproject`) or a WSL2 directory (e.g., `/home/mario/src/myproject`)?

According to what I see in [devcontainer.json]( https://code.visualstudio.com/docs/remote/devcontainerjson-reference) using ${localEnv:HOME} should be working if you open your folder from WSL2 itself (that is, from the embedded BASH, not a Windows Powershell or Cmd prompt). This is is what I do and it works.

If you want to open your remote container directly from a folder residing inside Windows (e.g., C:\src\myproject) than you probably don't have the same environment variables as in WSL2 environment (e.g., no $HOME).
According to [Microsoft Docs](https://code.visualstudio.com/remote/advancedcontainers/add-local-file-mount) you can write something like:

```
"source=${localEnv:HOME}${localEnv:USERPROFILE}/.gitconfig,target=/home/vscode/.gitconfig,type=bind,consistency=cache"
```
which should expand correctly depending on which environment you are.

Hope this helps.

**Comment by scalasm** [comment]
Thanks for your interest - I am closing this but feel free to reopen or suggest a PR!
